version: '3.8'
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    networks:
      - app-network
  app: 
    container_name: app
    build: .
    environment:
      - APP_NAME=kwan_challenge
      - SECRET=ultra_secret_pass
      - JWT_SECRET=ultra_secret_pass
      - DATABASE_URL="mysql://root:root@db:3306/app"
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=default
    ports: 
      - 3000:3000
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_HIPE_COMPILE: 0
    networks:
      - app-network

  worker:
    build: ./worker
    container_name: worker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=default
    depends_on:
      - rabbitmq
    restart: unless-stopped
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge