# Start from the latest golang base image
FROM golang:1.21.3


WORKDIR /worker/
# COPY go.mod ./go.mod
COPY go.sum go.sum ./ 

# Copy the source from the current directory to the Working Directory inside the container
COPY . .


ENV RABBITMQ_QUEUE='rqueue'
ENV RABBITMQ_HOST='rabbitmq'
ENV RABBITMQ_USER='admin'
ENV RABBITMQ_PASS='admin'
ENV RABBITMQ_PORT='5672'



RUN go mod download



CMD ["go","run","main.go"]